//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WebForm.cn.edu.ecnu.userinfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SMSWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SMSWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MySoapHeader mySoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback SMSSend_ZLWXOperationCompleted;
        
        private System.Threading.SendOrPostCallback WaitSMSSend_ZLWXOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySMSStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySMSUPOperationCompleted;
        
        private System.Threading.SendOrPostCallback YunPianSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback YunPianSendExOperationCompleted;
        
        private System.Threading.SendOrPostCallback YunPianSMSUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback YunPianCheckMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_UserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Set_UserInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SMSWebService() {
            this.Url = global::WebForm.Properties.Settings.Default.WebForm_cn_edu_ecnu_userinfo_SMSWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MySoapHeader MySoapHeaderValue {
            get {
                return this.mySoapHeaderValueField;
            }
            set {
                this.mySoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SMSSend_ZLWXCompletedEventHandler SMSSend_ZLWXCompleted;
        
        /// <remarks/>
        public event WaitSMSSend_ZLWXCompletedEventHandler WaitSMSSend_ZLWXCompleted;
        
        /// <remarks/>
        public event QuerySMSStateCompletedEventHandler QuerySMSStateCompleted;
        
        /// <remarks/>
        public event QuerySMSUPCompletedEventHandler QuerySMSUPCompleted;
        
        /// <remarks/>
        public event YunPianSendCompletedEventHandler YunPianSendCompleted;
        
        /// <remarks/>
        public event YunPianSendExCompletedEventHandler YunPianSendExCompleted;
        
        /// <remarks/>
        public event YunPianSMSUpCompletedEventHandler YunPianSMSUpCompleted;
        
        /// <remarks/>
        public event YunPianCheckMsgCompletedEventHandler YunPianCheckMsgCompleted;
        
        /// <remarks/>
        public event Get_UserInfoCompletedEventHandler Get_UserInfoCompleted;
        
        /// <remarks/>
        public event Set_UserInfoCompletedEventHandler Set_UserInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMSSend_ZLWX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMSSend_ZLWX(string phone, int formatid, string content, string scheduledate, string tokenID) {
            object[] results = this.Invoke("SMSSend_ZLWX", new object[] {
                        phone,
                        formatid,
                        content,
                        scheduledate,
                        tokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMSSend_ZLWXAsync(string phone, int formatid, string content, string scheduledate, string tokenID) {
            this.SMSSend_ZLWXAsync(phone, formatid, content, scheduledate, tokenID, null);
        }
        
        /// <remarks/>
        public void SMSSend_ZLWXAsync(string phone, int formatid, string content, string scheduledate, string tokenID, object userState) {
            if ((this.SMSSend_ZLWXOperationCompleted == null)) {
                this.SMSSend_ZLWXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMSSend_ZLWXOperationCompleted);
            }
            this.InvokeAsync("SMSSend_ZLWX", new object[] {
                        phone,
                        formatid,
                        content,
                        scheduledate,
                        tokenID}, this.SMSSend_ZLWXOperationCompleted, userState);
        }
        
        private void OnSMSSend_ZLWXOperationCompleted(object arg) {
            if ((this.SMSSend_ZLWXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMSSend_ZLWXCompleted(this, new SMSSend_ZLWXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WaitSMSSend_ZLWX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WaitSMSSend_ZLWX(string phone, int formatid, string content, System.DateTime ScheduleDate) {
            object[] results = this.Invoke("WaitSMSSend_ZLWX", new object[] {
                        phone,
                        formatid,
                        content,
                        ScheduleDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WaitSMSSend_ZLWXAsync(string phone, int formatid, string content, System.DateTime ScheduleDate) {
            this.WaitSMSSend_ZLWXAsync(phone, formatid, content, ScheduleDate, null);
        }
        
        /// <remarks/>
        public void WaitSMSSend_ZLWXAsync(string phone, int formatid, string content, System.DateTime ScheduleDate, object userState) {
            if ((this.WaitSMSSend_ZLWXOperationCompleted == null)) {
                this.WaitSMSSend_ZLWXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWaitSMSSend_ZLWXOperationCompleted);
            }
            this.InvokeAsync("WaitSMSSend_ZLWX", new object[] {
                        phone,
                        formatid,
                        content,
                        ScheduleDate}, this.WaitSMSSend_ZLWXOperationCompleted, userState);
        }
        
        private void OnWaitSMSSend_ZLWXOperationCompleted(object arg) {
            if ((this.WaitSMSSend_ZLWXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WaitSMSSend_ZLWXCompleted(this, new WaitSMSSend_ZLWXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySMSState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySMSState(string messageId) {
            object[] results = this.Invoke("QuerySMSState", new object[] {
                        messageId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySMSStateAsync(string messageId) {
            this.QuerySMSStateAsync(messageId, null);
        }
        
        /// <remarks/>
        public void QuerySMSStateAsync(string messageId, object userState) {
            if ((this.QuerySMSStateOperationCompleted == null)) {
                this.QuerySMSStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySMSStateOperationCompleted);
            }
            this.InvokeAsync("QuerySMSState", new object[] {
                        messageId}, this.QuerySMSStateOperationCompleted, userState);
        }
        
        private void OnQuerySMSStateOperationCompleted(object arg) {
            if ((this.QuerySMSStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySMSStateCompleted(this, new QuerySMSStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySMSUP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySMSUP(int MinID, int count, string sToken, string externCode) {
            object[] results = this.Invoke("QuerySMSUP", new object[] {
                        MinID,
                        count,
                        sToken,
                        externCode});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySMSUPAsync(int MinID, int count, string sToken, string externCode) {
            this.QuerySMSUPAsync(MinID, count, sToken, externCode, null);
        }
        
        /// <remarks/>
        public void QuerySMSUPAsync(int MinID, int count, string sToken, string externCode, object userState) {
            if ((this.QuerySMSUPOperationCompleted == null)) {
                this.QuerySMSUPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySMSUPOperationCompleted);
            }
            this.InvokeAsync("QuerySMSUP", new object[] {
                        MinID,
                        count,
                        sToken,
                        externCode}, this.QuerySMSUPOperationCompleted, userState);
        }
        
        private void OnQuerySMSUPOperationCompleted(object arg) {
            if ((this.QuerySMSUPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySMSUPCompleted(this, new QuerySMSUPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YunPianSend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YunPianSend(string phone, string content) {
            object[] results = this.Invoke("YunPianSend", new object[] {
                        phone,
                        content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YunPianSendAsync(string phone, string content) {
            this.YunPianSendAsync(phone, content, null);
        }
        
        /// <remarks/>
        public void YunPianSendAsync(string phone, string content, object userState) {
            if ((this.YunPianSendOperationCompleted == null)) {
                this.YunPianSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYunPianSendOperationCompleted);
            }
            this.InvokeAsync("YunPianSend", new object[] {
                        phone,
                        content}, this.YunPianSendOperationCompleted, userState);
        }
        
        private void OnYunPianSendOperationCompleted(object arg) {
            if ((this.YunPianSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YunPianSendCompleted(this, new YunPianSendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YunPianSendEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YunPianSendEx(string phone, string content, string extend) {
            object[] results = this.Invoke("YunPianSendEx", new object[] {
                        phone,
                        content,
                        extend});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YunPianSendExAsync(string phone, string content, string extend) {
            this.YunPianSendExAsync(phone, content, extend, null);
        }
        
        /// <remarks/>
        public void YunPianSendExAsync(string phone, string content, string extend, object userState) {
            if ((this.YunPianSendExOperationCompleted == null)) {
                this.YunPianSendExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYunPianSendExOperationCompleted);
            }
            this.InvokeAsync("YunPianSendEx", new object[] {
                        phone,
                        content,
                        extend}, this.YunPianSendExOperationCompleted, userState);
        }
        
        private void OnYunPianSendExOperationCompleted(object arg) {
            if ((this.YunPianSendExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YunPianSendExCompleted(this, new YunPianSendExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YunPianSMSUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YunPianSMSUp(string starttime, string endtime, string pagenum, string pagesize, string mobile) {
            object[] results = this.Invoke("YunPianSMSUp", new object[] {
                        starttime,
                        endtime,
                        pagenum,
                        pagesize,
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YunPianSMSUpAsync(string starttime, string endtime, string pagenum, string pagesize, string mobile) {
            this.YunPianSMSUpAsync(starttime, endtime, pagenum, pagesize, mobile, null);
        }
        
        /// <remarks/>
        public void YunPianSMSUpAsync(string starttime, string endtime, string pagenum, string pagesize, string mobile, object userState) {
            if ((this.YunPianSMSUpOperationCompleted == null)) {
                this.YunPianSMSUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYunPianSMSUpOperationCompleted);
            }
            this.InvokeAsync("YunPianSMSUp", new object[] {
                        starttime,
                        endtime,
                        pagenum,
                        pagesize,
                        mobile}, this.YunPianSMSUpOperationCompleted, userState);
        }
        
        private void OnYunPianSMSUpOperationCompleted(object arg) {
            if ((this.YunPianSMSUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YunPianSMSUpCompleted(this, new YunPianSMSUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YunPianCheckMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YunPianCheckMsg(string content) {
            object[] results = this.Invoke("YunPianCheckMsg", new object[] {
                        content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YunPianCheckMsgAsync(string content) {
            this.YunPianCheckMsgAsync(content, null);
        }
        
        /// <remarks/>
        public void YunPianCheckMsgAsync(string content, object userState) {
            if ((this.YunPianCheckMsgOperationCompleted == null)) {
                this.YunPianCheckMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYunPianCheckMsgOperationCompleted);
            }
            this.InvokeAsync("YunPianCheckMsg", new object[] {
                        content}, this.YunPianCheckMsgOperationCompleted, userState);
        }
        
        private void OnYunPianCheckMsgOperationCompleted(object arg) {
            if ((this.YunPianCheckMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YunPianCheckMsgCompleted(this, new YunPianCheckMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_UserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_UserInfo(string uid) {
            object[] results = this.Invoke("Get_UserInfo", new object[] {
                        uid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_UserInfoAsync(string uid) {
            this.Get_UserInfoAsync(uid, null);
        }
        
        /// <remarks/>
        public void Get_UserInfoAsync(string uid, object userState) {
            if ((this.Get_UserInfoOperationCompleted == null)) {
                this.Get_UserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_UserInfoOperationCompleted);
            }
            this.InvokeAsync("Get_UserInfo", new object[] {
                        uid}, this.Get_UserInfoOperationCompleted, userState);
        }
        
        private void OnGet_UserInfoOperationCompleted(object arg) {
            if ((this.Get_UserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_UserInfoCompleted(this, new Get_UserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_UserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Set_UserInfo(string uid, string mobile) {
            object[] results = this.Invoke("Set_UserInfo", new object[] {
                        uid,
                        mobile});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Set_UserInfoAsync(string uid, string mobile) {
            this.Set_UserInfoAsync(uid, mobile, null);
        }
        
        /// <remarks/>
        public void Set_UserInfoAsync(string uid, string mobile, object userState) {
            if ((this.Set_UserInfoOperationCompleted == null)) {
                this.Set_UserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_UserInfoOperationCompleted);
            }
            this.InvokeAsync("Set_UserInfo", new object[] {
                        uid,
                        mobile}, this.Set_UserInfoOperationCompleted, userState);
        }
        
        private void OnSet_UserInfoOperationCompleted(object arg) {
            if ((this.Set_UserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_UserInfoCompleted(this, new Set_UserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class MySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SMSSend_ZLWXCompletedEventHandler(object sender, SMSSend_ZLWXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMSSend_ZLWXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMSSend_ZLWXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void WaitSMSSend_ZLWXCompletedEventHandler(object sender, WaitSMSSend_ZLWXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WaitSMSSend_ZLWXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WaitSMSSend_ZLWXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QuerySMSStateCompletedEventHandler(object sender, QuerySMSStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySMSStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySMSStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QuerySMSUPCompletedEventHandler(object sender, QuerySMSUPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySMSUPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySMSUPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void YunPianSendCompletedEventHandler(object sender, YunPianSendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YunPianSendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YunPianSendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void YunPianSendExCompletedEventHandler(object sender, YunPianSendExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YunPianSendExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YunPianSendExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void YunPianSMSUpCompletedEventHandler(object sender, YunPianSMSUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YunPianSMSUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YunPianSMSUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void YunPianCheckMsgCompletedEventHandler(object sender, YunPianCheckMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YunPianCheckMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YunPianCheckMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void Get_UserInfoCompletedEventHandler(object sender, Get_UserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_UserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_UserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void Set_UserInfoCompletedEventHandler(object sender, Set_UserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_UserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_UserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591