//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleFoWo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organize
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.Guid ParentID { get; set; }
        public int Sort { get; set; }
        public int Depth { get; set; }
        public int ChildsLength { get; set; }
        public string ChargeLeader { get; set; }
        public string Leader { get; set; }
        public string Note { get; set; }
    }
}
